import { InterviewQuestion, QuestionCategory, Difficulty, RoleSlug, LevelSlug } from "../types";

export const interviewQuestions: InterviewQuestion[] = [
  {
    id: "q1",
    role: RoleSlug.FRONTEND,
    level: LevelSlug.MID,
    category: QuestionCategory.TECHNICAL,
    question: "Explain how closures work in JavaScript...",
    difficulty: Difficulty.MEDIUM,
    skills: ["JavaScript", "Closures", "Scope"],
    estimatedTime: "3-4 min",
    guidance: {
      keyPoints: ["Define closure as function retaining outer scope", "Lexical scoping", "Memory implications"],
      commonMistakes: ["Confusing closures with regular nested calls", "Assuming values are copied not referenced"],
      answerStructure: ["One-sentence definition", "Lexical scoping", "Code example", "Use cases", "Memory notes"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
  {
    id: "q2",
    role: RoleSlug.BACKEND,
    level: LevelSlug.JUNIOR,
    category: QuestionCategory.TECHNICAL,
    question: "What are the key differences between SQL and NoSQL databases?",
    difficulty: Difficulty.EASY,
    skills: ["Databases", "SQL", "NoSQL", "Architecture"],
    estimatedTime: "2-3 min",
    guidance: {
      keyPoints: ["SQL is relational, ACID", "NoSQL is non-relational, BASE", "Trade-offs: consistency vs scalability"],
      commonMistakes: ["Presenting one as universally better", "Forgetting polyglot persistence"],
      answerStructure: ["Categorize SQL vs NoSQL", "Compare structure", "Compare consistency", "Compare scalability", "Use case recommendations"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
  {
    id: "q3",
    role: RoleSlug.FRONTEND,
    level: LevelSlug.SENIOR,
    category: QuestionCategory.TECHNICAL,
    question: "Explain the JavaScript event loop. How do microtasks and macrotasks differ?",
    difficulty: Difficulty.MEDIUM,
    skills: ["JavaScript", "Event Loop", "Async", "Concurrency"],
    estimatedTime: "3-4 min",
    guidance: {
      keyPoints: ["Event loop handles async callbacks", "Microtask queue before macrotask queue"],
      commonMistakes: ["setTimeout(fn,0) is not immediate", "Forgetting rAF is its own queue"],
      answerStructure: ["Single-threaded with call stack", "Async delegated to environment", "Loop: stack → micro → macro"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
  {
    id: "q4",
    role: RoleSlug.DATA_ENGINEER,
    level: LevelSlug.MID,
    category: QuestionCategory.TECHNICAL,
    question: "What is database normalization? Explain 1NF, 2NF, and 3NF.",
    difficulty: Difficulty.EASY,
    skills: ["Databases", "SQL", "Normalization", "Data Modeling"],
    estimatedTime: "3-4 min",
    guidance: {
      keyPoints: ["Reduces redundancy", "1NF: atomic values", "2NF: no partial dependency", "3NF: no transitive dependency"],
      commonMistakes: ["Mixing 2NF and 3NF", "Over-normalizing"],
      answerStructure: ["Define normalization", "1NF example", "2NF example", "3NF example", "Trade-offs"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
  {
    id: "q5",
    role: RoleSlug.DEVOPS,
    level: LevelSlug.SENIOR,
    category: QuestionCategory.TECHNICAL,
    question: "Design a CI/CD pipeline for microservices. What stages?",
    difficulty: Difficulty.HARD,
    skills: ["CI/CD", "DevOps", "Microservices", "Docker"],
    estimatedTime: "4-5 min",
    guidance: {
      keyPoints: ["Source → Build → Test → Deploy", "Per-service pipeline", "Canary or blue-green"],
      commonMistakes: ["Single pipeline for all services", "No rollback strategy"],
      answerStructure: ["Goal: automated safe delivery", "Trigger", "Stages walkthrough", "Scale across services", "Observability"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
  {
    id: "q6",
    role: RoleSlug.SYSTEMS_ENGINEER,
    level: LevelSlug.SENIOR,
    category: QuestionCategory.PROBLEM_SOLVING,
    question: "Design a URL shortening service. Consider scale and latency.",
    difficulty: Difficulty.HARD,
    skills: ["System Design", "Distributed Systems", "Databases", "Caching"],
    estimatedTime: "5-6 min",
    guidance: {
      keyPoints: ["Map short key to long URL", "Base62 encoding", "Redis caching", "301 vs 302 redirect"],
      commonMistakes: ["Auto-increment without distributed generation", "No cleanup strategy"],
      answerStructure: ["Clarify requirements", "API design", "Key generation", "Data model", "Caching", "Trade-offs"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
  {
    id: "q7",
    role: RoleSlug.BACKEND,
    level: LevelSlug.MID,
    category: QuestionCategory.PROBLEM_SOLVING,
    question: "Reverse a linked list iteratively and recursively.",
    difficulty: Difficulty.MEDIUM,
    skills: ["Data Structures", "Algorithms", "Linked Lists"],
    estimatedTime: "3-4 min",
    guidance: {
      keyPoints: ["Iterative: three pointers", "Recursive: unwind phase", "O(n) time"],
      commonMistakes: ["Losing next reference", "Forgetting head.next = null in recursive"],
      answerStructure: ["Clarify problem", "Iterative approach", "Recursive approach", "Compare trade-offs", "Edge cases"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
  {
    id: "q8",
    role: RoleSlug.SYSTEMS_ENGINEER,
    level: LevelSlug.SENIOR,
    category: QuestionCategory.PROBLEM_SOLVING,
    question: "Walk through your production outage debugging process.",
    difficulty: Difficulty.HARD,
    skills: ["Incident Response", "Debugging", "Observability", "SRE"],
    estimatedTime: "4-5 min",
    guidance: {
      keyPoints: ["Assess severity", "Stop the bleeding first", "Diagnose", "Communicate", "Post-mortem"],
      commonMistakes: ["Debugging before stopping damage", "No communication"],
      answerStructure: ["Assess impact", "Stop bleeding", "Communicate", "Diagnose", "Fix", "Post-mortem"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
  {
    id: "q9",
    role: RoleSlug.FRONTEND,
    level: LevelSlug.JUNIOR,
    category: QuestionCategory.BEHAVIORAL,
    question: "Tell me about a disagreement with a teammate over a technical decision.",
    difficulty: Difficulty.EASY,
    skills: ["Communication", "Conflict Resolution", "Collaboration"],
    estimatedTime: "2-3 min",
    guidance: {
      keyPoints: ["Use STAR method", "Show respect", "Focus on data"],
      commonMistakes: ["Making other sound unreasonable", "No self-reflection"],
      answerStructure: ["Situation + Task", "Disagreement", "Actions taken", "Outcome", "Reflection"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
  {
    id: "q10",
    role: RoleSlug.BACKEND,
    level: LevelSlug.MID,
    category: QuestionCategory.BEHAVIORAL,
    question: "Describe a project you're most proud of and your role.",
    difficulty: Difficulty.MEDIUM,
    skills: ["Leadership", "Ownership", "Impact"],
    estimatedTime: "2-3 min",
    guidance: {
      keyPoints: ["Clear ownership", "Quantify impact", "Technical challenges"],
      commonMistakes: ["No measurable impact", "Taking sole credit"],
      answerStructure: ["Project context", "Your role", "Key challenge", "Results", "What you learned"],
    },
    createdAt: "2026-06-11T12:00:00.000Z",
  },
];
