import { Job } from "../types/job";

export const jobListings: Job[] = [
  {
    id: "1",
    type: "scraped",
    title: "Senior Software Engineer",
    description:
      "We are looking for an experienced Senior Software Engineer to join our team.",
    company: {
      id: "c1",
      name: "Google",
      logo: "",
      website: "https://google.com",
      size: "10000+",
      industry: "Technology",
      location: "Mountain View, CA",
    },
    location: "Mountain View, CA",
    workArrangement: "hybrid",
    employmentType: "full-time",
    experienceLevel: "senior",
    salaryMin: 150000,
    salaryMax: 200000,
    skills: [
      { id: "s1", name: "JavaScript", category: "programming" },
      { id: "s2", name: "React", category: "frontend" },
    ],
    publishedAt: "2024-01-15T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 1247,
    applicationsCount: 47,
    status: "published",
    isFeatured: true,
    url: "https://linkedin.com",
    category: "Technology",
    salary: "$150-200K/yr",
    source: "LinkedIn",
    sourceColor: "#0A66C2",
    postedDate: "2 days ago",
    applicants: 47,
  },
  {
    id: "2",
    type: "direct",
    title: "Cloud Solutions Architect",
    description: "Join our cloud infrastructure team.",
    company: {
      id: "c2",
      name: "Microsoft",
      logo: "",
      website: "https://microsoft.com",
      size: "10000+",
      industry: "Technology",
      location: "Seattle, WA",
    },
    location: "Seattle, WA (Hybrid)",
    workArrangement: "hybrid",
    employmentType: "full-time",
    experienceLevel: "senior",
    salaryMin: 140000,
    salaryMax: 190000,
    skills: [
      { id: "s3", name: "Azure", category: "cloud" },
      { id: "s4", name: "DevOps", category: "operations" },
    ],
    publishedAt: "2024-01-16T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 892,
    applicationsCount: 32,
    status: "published",
    isFeatured: true,
    url: null,
    category: "Technology",
    salary: "$140-190K/yr",
    source: "Carrerk",
    sourceColor: "#0353a4",
    postedDate: "1 day ago",
    applicants: 32,
  },
  {
    id: "3",
    type: "scraped",
    title: "Product Manager",
    description: "Lead product strategy and development.",
    company: {
      id: "c3",
      name: "Amazon",
      logo: "",
      website: "https://amazon.com",
      size: "10000+",
      industry: "E-commerce & Technology",
      location: "Austin, TX",
    },
    location: "Austin, TX",
    workArrangement: "onsite",
    employmentType: "full-time",
    experienceLevel: "mid",
    salaryMin: 130000,
    salaryMax: 180000,
    skills: [
      { id: "s5", name: "Product Management", category: "management" },
      { id: "s6", name: "Agile", category: "methodology" },
    ],
    publishedAt: "2024-01-14T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 1500,
    applicationsCount: 89,
    status: "published",
    isFeatured: false,
    url: "https://glassdoor.com",
    category: "E-commerce & Technology",
    salary: "$130-180K/yr",
    source: "Glassdoor",
    sourceColor: "#0CAA41",
    postedDate: "3 days ago",
    applicants: 89,
  },
  {
    id: "4",
    type: "direct",
    title: "Machine Learning Engineer",
    description: "Build cutting-edge ML models.",
    company: {
      id: "c4",
      name: "Meta",
      logo: "",
      website: "https://meta.com",
      size: "10000+",
      industry: "Social Media & Tech",
      location: "Menlo Park, CA",
    },
    location: "Menlo Park, CA",
    workArrangement: "hybrid",
    employmentType: "full-time",
    experienceLevel: "senior",
    salaryMin: 160000,
    salaryMax: 220000,
    skills: [
      { id: "s7", name: "Python", category: "programming" },
      { id: "s8", name: "TensorFlow", category: "ml" },
    ],
    publishedAt: "2024-01-12T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 2100,
    applicationsCount: 124,
    status: "published",
    isFeatured: true,
    url: null,
    category: "Social Media & Tech",
    salary: "$160-220K/yr",
    source: "LinkedIn",
    sourceColor: "#0A66C2",
    postedDate: "5 days ago",
    applicants: 124,
  },
  {
    id: "5",
    type: "scraped",
    title: "iOS Developer",
    description: "Create amazing iOS experiences.",
    company: {
      id: "c5",
      name: "Apple",
      logo: "",
      website: "https://apple.com",
      size: "10000+",
      industry: "Technology & Hardware",
      location: "Cupertino, CA",
    },
    location: "Cupertino, CA",
    workArrangement: "onsite",
    employmentType: "full-time",
    experienceLevel: "mid",
    salaryMin: 145000,
    salaryMax: 195000,
    skills: [
      { id: "s9", name: "Swift", category: "programming" },
      { id: "s10", name: "iOS", category: "mobile" },
    ],
    publishedAt: "2024-01-10T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 950,
    applicationsCount: 56,
    status: "published",
    isFeatured: false,
    url: "https://wuzzuf.net",
    category: "Technology & Hardware",
    salary: "$145-195K/yr",
    source: "Wuzzuf",
    sourceColor: "#FF6B35",
    postedDate: "1 week ago",
    applicants: 56,
  },
  {
    id: "6",
    type: "direct",
    title: "Data Scientist",
    description: "Analyze data and build predictive models.",
    company: {
      id: "c6",
      name: "Netflix",
      logo: "",
      website: "https://netflix.com",
      size: "5000-10000",
      industry: "Entertainment & Streaming",
      location: "Los Gatos, CA",
    },
    location: "Los Gatos, CA (Remote)",
    workArrangement: "remote",
    employmentType: "full-time",
    experienceLevel: "mid",
    salaryMin: 135000,
    salaryMax: 185000,
    skills: [
      { id: "s11", name: "Python", category: "programming" },
      { id: "s12", name: "SQL", category: "database" },
    ],
    publishedAt: "2024-01-13T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 1320,
    applicationsCount: 78,
    status: "published",
    isFeatured: false,
    url: null,
    category: "Entertainment & Streaming",
    salary: "$135-185K/yr",
    source: "Indeed",
    sourceColor: "#2164F3",
    postedDate: "4 days ago",
    applicants: 78,
  },
  {
    id: "7",
    type: "scraped",
    title: "Mechanical Engineer",
    description: "Design and develop mechanical systems.",
    company: {
      id: "c7",
      name: "Tesla",
      logo: "",
      website: "https://tesla.com",
      size: "5000-10000",
      industry: "Automotive & Energy",
      location: "Fremont, CA",
    },
    location: "Fremont, CA",
    workArrangement: "onsite",
    employmentType: "full-time",
    experienceLevel: "mid",
    salaryMin: 110000,
    salaryMax: 160000,
    skills: [
      { id: "s13", name: "CAD", category: "engineering" },
      { id: "s14", name: "Mechanical Design", category: "engineering" },
    ],
    publishedAt: "2024-01-11T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 680,
    applicationsCount: 43,
    status: "published",
    isFeatured: false,
    url: "https://carrerk.com",
    category: "Automotive & Energy",
    salary: "$110-160K/yr",
    source: "Carrerk",
    sourceColor: "#0353a4",
    postedDate: "6 days ago",
    applicants: 43,
  },
  {
    id: "8",
    type: "direct",
    title: "UX Designer",
    description: "Create beautiful user experiences.",
    company: {
      id: "c8",
      name: "Salesforce",
      logo: "",
      website: "https://salesforce.com",
      size: "10000+",
      industry: "Enterprise Software",
      location: "San Francisco, CA",
    },
    location: "San Francisco, CA (Hybrid)",
    workArrangement: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid",
    salaryMin: 120000,
    salaryMax: 170000,
    skills: [
      { id: "s15", name: "Figma", category: "design" },
      { id: "s16", name: "UX Research", category: "design" },
    ],
    publishedAt: "2024-01-15T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 1100,
    applicationsCount: 61,
    status: "published",
    isFeatured: false,
    url: null,
    category: "Enterprise Software",
    salary: "$120-170K/yr",
    source: "LinkedIn",
    sourceColor: "#0A66C2",
    postedDate: "2 days ago",
    applicants: 61,
  },
  {
    id: "9",
    type: "scraped",
    title: "Frontend Developer",
    description: "Build responsive web applications.",
    company: {
      id: "c9",
      name: "Adobe",
      logo: "",
      website: "https://adobe.com",
      size: "5000-10000",
      industry: "Creative Software",
      location: "San Jose, CA",
    },
    location: "San Jose, CA",
    workArrangement: "hybrid",
    employmentType: "full-time",
    experienceLevel: "mid",
    salaryMin: 125000,
    salaryMax: 175000,
    skills: [
      { id: "s17", name: "React", category: "frontend" },
      { id: "s18", name: "TypeScript", category: "programming" },
    ],
    publishedAt: "2024-01-14T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 890,
    applicationsCount: 52,
    status: "published",
    isFeatured: false,
    url: "https://glassdoor.com",
    category: "Creative Software",
    salary: "$125-175K/yr",
    source: "Glassdoor",
    sourceColor: "#0CAA41",
    postedDate: "3 days ago",
    applicants: 52,
  },
  {
    id: "10",
    type: "direct",
    title: "Backend Engineer",
    description: "Build scalable backend systems.",
    company: {
      id: "c10",
      name: "Spotify",
      logo: "",
      website: "https://spotify.com",
      size: "1000-5000",
      industry: "Music & Entertainment",
      location: "New York, NY",
    },
    location: "New York, NY (Remote)",
    workArrangement: "remote",
    employmentType: "full-time",
    experienceLevel: "senior",
    salaryMin: 130000,
    salaryMax: 180000,
    skills: [
      { id: "s19", name: "Node.js", category: "backend" },
      { id: "s20", name: "PostgreSQL", category: "database" },
    ],
    publishedAt: "2024-01-16T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 1240,
    applicationsCount: 67,
    status: "published",
    isFeatured: true,
    url: null,
    category: "Music & Entertainment",
    salary: "$130-180K/yr",
    source: "Carrerk",
    sourceColor: "#0353a4",
    postedDate: "1 day ago",
    applicants: 67,
  },
  {
    id: "11",
    type: "scraped",
    title: "Product Designer",
    description: "Design innovative product experiences.",
    company: {
      id: "c11",
      name: "Airbnb",
      logo: "",
      website: "https://airbnb.com",
      size: "1000-5000",
      industry: "Travel & Hospitality",
      location: "San Francisco, CA",
    },
    location: "San Francisco, CA",
    workArrangement: "hybrid",
    employmentType: "full-time",
    experienceLevel: "senior",
    salaryMin: 140000,
    salaryMax: 190000,
    skills: [
      { id: "s21", name: "Product Design", category: "design" },
      { id: "s22", name: "Prototyping", category: "design" },
    ],
    publishedAt: "2024-01-15T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 1580,
    applicationsCount: 91,
    status: "published",
    isFeatured: false,
    url: "https://indeed.com",
    category: "Travel & Hospitality",
    salary: "$140-190K/yr",
    source: "Indeed",
    sourceColor: "#2164F3",
    postedDate: "2 days ago",
    applicants: 91,
  },
  {
    id: "12",
    type: "direct",
    title: "DevOps Engineer",
    description: "Manage infrastructure and deployments.",
    company: {
      id: "c12",
      name: "Uber",
      logo: "",
      website: "https://uber.com",
      size: "5000-10000",
      industry: "Transportation & Tech",
      location: "San Francisco, CA",
    },
    location: "San Francisco, CA",
    workArrangement: "onsite",
    employmentType: "full-time",
    experienceLevel: "mid",
    salaryMin: 135000,
    salaryMax: 185000,
    skills: [
      { id: "s23", name: "Kubernetes", category: "operations" },
      { id: "s24", name: "Docker", category: "operations" },
    ],
    publishedAt: "2024-01-12T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 720,
    applicationsCount: 38,
    status: "published",
    isFeatured: false,
    url: null,
    category: "Transportation & Tech",
    salary: "$135-185K/yr",
    source: "Wuzzuf",
    sourceColor: "#FF6B35",
    postedDate: "5 days ago",
    applicants: 38,
  },
  {
    id: "13",
    type: "scraped",
    title: "Full Stack Engineer",
    description: "Work across the entire stack.",
    company: {
      id: "c13",
      name: "Stripe",
      logo: "",
      website: "https://stripe.com",
      size: "1000-5000",
      industry: "Fintech",
      location: "Remote",
    },
    location: "Remote",
    workArrangement: "remote",
    employmentType: "full-time",
    experienceLevel: "senior",
    salaryMin: 155000,
    salaryMax: 205000,
    skills: [
      { id: "s25", name: "Ruby", category: "backend" },
      { id: "s26", name: "React", category: "frontend" },
    ],
    publishedAt: "2024-01-16T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 1890,
    applicationsCount: 103,
    status: "published",
    isFeatured: true,
    url: "https://carrerk.com",
    category: "Fintech",
    salary: "$155-205K/yr",
    source: "Carrerk",
    sourceColor: "#0353a4",
    postedDate: "1 day ago",
    applicants: 103,
  },
  {
    id: "14",
    type: "direct",
    title: "Software Engineer",
    description: "Build scalable e-commerce solutions.",
    company: {
      id: "c14",
      name: "Shopify",
      logo: "",
      website: "https://shopify.com",
      size: "5000-10000",
      industry: "E-commerce",
      location: "Ottawa, Canada",
    },
    location: "Ottawa, Canada (Remote)",
    workArrangement: "remote",
    employmentType: "full-time",
    experienceLevel: "mid",
    salaryMin: 120000,
    salaryMax: 170000,
    skills: [
      { id: "s27", name: "Ruby on Rails", category: "backend" },
      { id: "s28", name: "GraphQL", category: "api" },
    ],
    publishedAt: "2024-01-13T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 1050,
    applicationsCount: 74,
    status: "published",
    isFeatured: false,
    url: null,
    category: "E-commerce",
    salary: "$120-170K/yr",
    source: "LinkedIn",
    sourceColor: "#0A66C2",
    postedDate: "4 days ago",
    applicants: 74,
  },
  {
    id: "15",
    type: "scraped",
    title: "Senior Product Manager",
    description: "Lead product strategy and vision.",
    company: {
      id: "c15",
      name: "Slack",
      logo: "",
      website: "https://slack.com",
      size: "1000-5000",
      industry: "Communication & Collaboration",
      location: "San Francisco, CA",
    },
    location: "San Francisco, CA (Hybrid)",
    workArrangement: "hybrid",
    employmentType: "full-time",
    experienceLevel: "senior",
    salaryMin: 145000,
    salaryMax: 195000,
    skills: [
      { id: "s29", name: "Product Strategy", category: "management" },
      { id: "s30", name: "Data Analysis", category: "analytics" },
    ],
    publishedAt: "2024-01-14T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 1420,
    applicationsCount: 85,
    status: "published",
    isFeatured: false,
    url: "https://glassdoor.com",
    category: "Communication & Collaboration",
    salary: "$145-195K/yr",
    source: "Glassdoor",
    sourceColor: "#0CAA41",
    postedDate: "3 days ago",
    applicants: 85,
  },
  {
    id: "16",
    type: "direct",
    title: "QA Engineer",
    description: "Ensure quality across our products.",
    company: {
      id: "c16",
      name: "Zoom",
      logo: "",
      website: "https://zoom.us",
      size: "1000-5000",
      industry: "Video Communications",
      location: "San Jose, CA",
    },
    location: "San Jose, CA",
    workArrangement: "onsite",
    employmentType: "full-time",
    experienceLevel: "entry",
    salaryMin: 100000,
    salaryMax: 140000,
    skills: [
      { id: "s31", name: "Test Automation", category: "testing" },
      { id: "s32", name: "Selenium", category: "testing" },
    ],
    publishedAt: "2024-01-11T10:30:00Z",
    applicationDeadline: null,
    viewsCount: 560,
    applicationsCount: 29,
    status: "published",
    isFeatured: false,
    url: null,
    category: "Video Communications",
    salary: "$100-140K/yr",
    source: "Indeed",
    sourceColor: "#2164F3",
    postedDate: "6 days ago",
    applicants: 29,
  },
];
