import { Job } from "../types/job";

export const matchedJobs: Job[] = [
  {
    id: "1",
    type: "scraped",
    title: "Senior Software Engineer",
    description:
      "We are looking for an experienced Senior Software Engineer to join our team.",
    companyName: "Google",
    location: "Mountain View, CA",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    skills: [
      { skillId: "s1", name: "JavaScript" },
      { skillId: "s2", name: "React" },
    ],
    sourceUrl: "https://linkedin.com",
    salary: "$150-200K/yr",
    source: "LinkedIn",
    postedAt: "2024-01-15T10:30:00.000Z",
    matchScore: 85,
  },
  {
    id: "2",
    type: "direct",
    title: "Cloud Solutions Architect",
    description: "Join our cloud infrastructure team.",
    company: {
      id: "c2",
      name: "Microsoft",
      logoUrl: "",
      industry: "Technology",
    },
    location: "Seattle, WA (Hybrid)",
    workPreference: "HYBRID",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    salaryMin: 140000,
    salaryMax: 190000,
    skills: [
      { skillId: "s3", name: "Azure" },
      { skillId: "s4", name: "DevOps" },
    ],
    publishedAt: "2024-01-16T10:30:00Z",
    source: "Careerk",
    applicants: 32,
    matchScore: 90,
  },
  {
    id: "3",
    type: "scraped",
    title: "Product Manager",
    description: "Lead product strategy and development.",
    companyName: "Amazon",
    location: "Austin, TX",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    skills: [
      { skillId: "s5", name: "Product Management" },
      { skillId: "s6", name: "Agile" },
    ],
    sourceUrl: "https://glassdoor.com",
    salary: "$130-180K/yr",
    source: "Glassdoor",
    postedAt: "2024-01-14T10:30:00.000Z",
    matchScore: 75,
  },
  {
    id: "4",
    type: "direct",
    title: "Machine Learning Engineer",
    description: "Build cutting-edge ML models.",
    company: {
      id: "c4",
      name: "Meta",
      logoUrl: "",
      industry: "Social Media & Tech",
    },
    location: "Menlo Park, CA",
    workPreference: "HYBRID",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    salaryMin: 160000,
    salaryMax: 220000,
    skills: [
      { skillId: "s7", name: "Python" },
      { skillId: "s8", name: "TensorFlow" },
    ],
    publishedAt: "2024-01-12T10:30:00Z",
    source: "LinkedIn",
    applicants: 124,
    matchScore: 80,
  },
  {
    id: "5",
    type: "scraped",
    title: "iOS Developer",
    description: "Create amazing iOS experiences.",
    companyName: "Apple",
    location: "Cupertino, CA",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    skills: [
      { skillId: "s9", name: "Swift" },
      { skillId: "s10", name: "iOS" },
    ],
    sourceUrl: "https://wuzzuf.net",
    salary: "$145-195K/yr",
    source: "Wuzzuf",
    postedAt: "2024-01-10T10:30:00.000Z",
  },
  {
    id: "6",
    type: "direct",
    title: "Data Scientist",
    description: "Analyze data and build predictive models.",
    company: {
      id: "c6",
      name: "Netflix",
      logoUrl: "",
      industry: "Entertainment & Streaming",
    },
    location: "Los Gatos, CA (Remote)",
    workPreference: "REMOTE",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 135000,
    salaryMax: 185000,
    skills: [
      { skillId: "s11", name: "Python" },
      { skillId: "s12", name: "SQL" },
    ],
    publishedAt: "2024-01-13T10:30:00Z",
    source: "Indeed",
    applicants: 78,
    matchScore: 85,
  },
  {
    id: "7",
    type: "scraped",
    title: "Mechanical Engineer",
    description: "Design and develop mechanical systems.",
    companyName: "Tesla",
    location: "Fremont, CA",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    skills: [
      { skillId: "s13", name: "CAD" },
      { skillId: "s14", name: "Mechanical Design" },
    ],
    sourceUrl: "https://Careerk.com",
    salary: "$110-160K/yr",
    source: "Careerk",
    postedAt: "2024-01-11T10:30:00.000Z",
    matchScore: 70,
  },
  {
    id: "8",
    type: "direct",
    title: "UX Designer",
    description: "Create beautiful user experiences.",
    company: {
      id: "c8",
      name: "Salesforce",
      logoUrl: "",
      industry: "Enterprise Software",
    },
    location: "San Francisco, CA (Hybrid)",
    workPreference: "HYBRID",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 120000,
    salaryMax: 170000,
    skills: [
      { skillId: "s15", name: "Figma" },
      { skillId: "s16", name: "UX Research" },
    ],
    publishedAt: "2024-01-15T10:30:00Z",
    source: "LinkedIn",
    applicants: 61,
    matchScore: 85,
  },
  {
    id: "9",
    type: "scraped",
    title: "Frontend Developer",
    description: "Build responsive web applications.",
    companyName: "Adobe",
    location: "San Jose, CA",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    skills: [
      { skillId: "s17", name: "React" },
      { skillId: "s18", name: "TypeScript" },
    ],
    sourceUrl: "https://glassdoor.com",
    salary: "$125-175K/yr",
    source: "Glassdoor",
    postedAt: "2024-01-14T10:30:00.000Z",
    matchScore: 80,
  },
  {
    id: "10",
    type: "direct",
    title: "Backend Engineer",
    description: "Build scalable backend systems.",
    company: {
      id: "c10",
      name: "Spotify",
      logoUrl: "",
      industry: "Music & Entertainment",
    },
    location: "New York, NY (Remote)",
    workPreference: "REMOTE",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    salaryMin: 130000,
    salaryMax: 180000,
    skills: [
      { skillId: "s19", name: "Node.js" },
      { skillId: "s20", name: "PostgreSQL" },
    ],
    publishedAt: "2024-01-16T10:30:00Z",
    source: "Careerk",
    applicants: 67,
    matchScore: 85,
  },
  {
    id: "11",
    type: "scraped",
    title: "Product Designer",
    description: "Design innovative product experiences.",
    companyName: "Airbnb",
    location: "San Francisco, CA",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    skills: [
      { skillId: "s21", name: "Product Design" },
      { skillId: "s22", name: "Prototyping" },
    ],
    sourceUrl: "https://indeed.com",
    salary: "$140-190K/yr",
    source: "Indeed",
    postedAt: "2024-01-15T10:30:00.000Z",
    matchScore: 90,
  },
  {
    id: "12",
    type: "direct",
    title: "DevOps Engineer",
    description: "Manage infrastructure and deployments.",
    company: {
      id: "c12",
      name: "Uber",
      logoUrl: "",
      industry: "Transportation & Tech",
    },
    location: "San Francisco, CA",
    workPreference: "ONSITE",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 135000,
    salaryMax: 185000,
    skills: [
      { skillId: "s23", name: "Kubernetes" },
      { skillId: "s24", name: "Docker" },
    ],
    publishedAt: "2024-01-12T10:30:00Z",
    source: "Wuzzuf",
    applicants: 38,
    matchScore: 75,
  },
  {
    id: "13",
    type: "scraped",
    title: "Full Stack Engineer",
    description: "Work across the entire stack.",
    companyName: "Stripe",
    location: "Remote",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    skills: [
      { skillId: "s25", name: "Ruby" },
      { skillId: "s26", name: "React" },
    ],
    sourceUrl: "https://Careerk.com",
    salary: "$155-205K/yr",
    source: "Careerk",
    postedAt: "2024-01-16T10:30:00.000Z",
  },
  {
    id: "14",
    type: "direct",
    title: "Software Engineer",
    description: "Build scalable e-commerce solutions.",
    company: {
      id: "c14",
      name: "Shopify",
      logoUrl: "",
      industry: "E-commerce",
    },
    location: "Ottawa, Canada (Remote)",
    workPreference: "REMOTE",
    jobType: "FULL_TIME",
    experienceLevel: "MID",
    salaryMin: 120000,
    salaryMax: 170000,
    skills: [
      { skillId: "s27", name: "Ruby on Rails" },
      { skillId: "s28", name: "GraphQL" },
    ],
    publishedAt: "2024-01-13T10:30:00Z",
    source: "LinkedIn",
    applicants: 74,
    matchScore: 85,
  },
  {
    id: "15",
    type: "scraped",
    title: "Senior Product Manager",
    description: "Lead product strategy and vision.",
    companyName: "Slack",
    location: "San Francisco, CA (Hybrid)",
    jobType: "FULL_TIME",
    experienceLevel: "SENIOR",
    skills: [
      { skillId: "s29", name: "Product Strategy" },
      { skillId: "s30", name: "Data Analysis" },
    ],
    sourceUrl: "https://glassdoor.com",
    salary: "$145-195K/yr",
    source: "Glassdoor",
    postedAt: "2024-01-14T10:30:00.000Z",
    matchScore: 70,
  },
  {
    id: "16",
    type: "direct",
    title: "QA Engineer",
    description: "Ensure quality across our products.",
    company: {
      id: "c16",
      name: "Zoom",
      logoUrl: "",
      industry: "Video Communications",
    },
    location: "San Jose, CA",
    workPreference: "ONSITE",
    jobType: "FULL_TIME",
    experienceLevel: "ENTRY",
    salaryMin: 100000,
    salaryMax: 140000,
    skills: [
      { skillId: "s31", name: "Test Automation" },
      { skillId: "s32", name: "Selenium" },
    ],
    publishedAt: "2024-01-11T10:30:00Z",
    source: "Indeed",
    applicants: 29,
    matchScore: 85,
  },
];
