import { Candidate } from "@/entities/candidate";

export const candidates: Candidate[] = [
  {
    id: "cand-1",
    user_id: "u1",
    name: "Amina Hassan",
    jobTitle: "Frontend Engineer",
    experienceLevel: "Mid Level",
    skills: ["React", "TypeScript", "Next.js", "CSS", "Tailwind"],
    title: "Frontend Engineer — React / Next.js",
    email: "amina.hassan@example.com",
    phone: "+20-100-000-0001",
    summary:
      "4+ years building responsive web apps and component libraries. Strong focus on performance and accessibility.",
    location: "Cairo, Egypt",
    cv_score: 72,
    cv_match_percentage: 68,
    availability_status: "Open to Offers",
    expected_salary: 60000,
    work_preference: "hybrid",
    linkedin_url: "https://linkedin.com/in/amina-hassan",
    portfolio_url: "https://amina.dev",
    github_url: "https://github.com/aminahassan",
    avatarUrl: null,
    created_at: new Date("2025-06-18T09:30:00Z"),
    updated_at: new Date("2025-12-01T12:00:00Z"),
  },

  {
    id: "cand-2",
    user_id: "u2",
    name: "John Carter",
    jobTitle: "Backend Engineer",
    experienceLevel: "Senior Level",
    skills: ["Node.js", "TypeScript", "PostgreSQL", "Docker", "AWS"],
    title: "Senior Backend Engineer — APIs & Scalability",
    email: "john.carter@example.com",
    phone: "+1-415-555-0123",
    summary:
      "Backend engineer with a track record of building high-throughput services and microservice architectures.",
    location: "San Francisco, CA, USA",
    cv_score: 88,
    cv_match_percentage: 91,
    availability_status: "Available",
    expected_salary: 130000,
    work_preference: "remote",
    linkedin_url: "https://linkedin.com/in/johncarter",
    portfolio_url: null,
    github_url: "https://github.com/johncarter-dev",
    avatarUrl: null,
    created_at: new Date("2024-11-02T08:15:00Z"),
    updated_at: new Date("2026-01-10T09:45:00Z"),
  },

  {
    id: "cand-3",
    user_id: "u3",
    name: "María López",
    jobTitle: "Data Analyst",
    experienceLevel: "Entry Level",
    skills: ["SQL", "Python", "Pandas", "Excel", "Tableau"],
    title: "Data Analyst — SQL & Python",
    email: "maria.lopez@example.com",
    phone: null,
    summary:
      "Entry-level analyst with internship experience in data cleaning, visualization and reporting.",
    location: "Bogotá, Colombia",
    cv_score: 65,
    cv_match_percentage: 60,
    availability_status: "Open to Offers",
    expected_salary: 48000,
    work_preference: "on-site",
    linkedin_url: "https://linkedin.com/in/marialopez",
    portfolio_url: null,
    github_url: "https://github.com/marialopez",
    avatarUrl: null,
    created_at: new Date("2025-02-14T14:20:00Z"),
    updated_at: new Date("2025-10-21T07:30:00Z"),
  },

  {
    id: "cand-4",
    user_id: "u4",
    name: "Chen Wei",
    jobTitle: "Machine Learning Engineer",
    experienceLevel: "Lead",
    skills: ["Python", "TensorFlow", "PyTorch", "ML Ops", "Kubernetes"],
    title: "Lead ML Engineer — Production ML",
    email: "chen.wei@example.com",
    phone: "+86-10-8888-0004",
    summary:
      "Led ML platform initiatives and productionized several large-scale models for recommendation and forecasting.",
    location: "Beijing, China",
    cv_score: 95,
    cv_match_percentage: 92,
    availability_status: "Not Available",
    expected_salary: 180000,
    work_preference: "hybrid",
    linkedin_url: "https://linkedin.com/in/chenwei-ml",
    portfolio_url: null,
    github_url: "https://github.com/chenwei-ml",
    avatarUrl: null,
    created_at: new Date("2023-09-05T11:00:00Z"),
    updated_at: new Date("2025-09-18T10:10:00Z"),
  },

  {
    id: "cand-5",
    user_id: "u5",
    name: "Samuel Okoye",
    jobTitle: "Fullstack Developer",
    experienceLevel: "Mid Level",
    skills: ["React", "Node.js", "GraphQL", "TypeScript", "Prisma"],
    title: "Fullstack Developer — JavaScript/TypeScript",
    email: "samuel.okoye@example.com",
    phone: "+234-80-0000-0005",
    summary:
      "Fullstack developer experienced in end-to-end feature delivery and API design.",
    location: "Lagos, Nigeria",
    cv_score: 77,
    cv_match_percentage: 73,
    availability_status: "Available",
    expected_salary: 80000,
    work_preference: "remote",
    linkedin_url: "https://linkedin.com/in/samuelokoye",
    portfolio_url: "https://samuel.dev",
    github_url: "https://github.com/samuelokoye",
    avatarUrl: null,
    created_at: new Date("2024-03-12T09:00:00Z"),
    updated_at: new Date("2026-01-05T16:20:00Z"),
  },

  {
    id: "cand-6",
    user_id: "u6",
    name: "Elena Petrova",
    jobTitle: "Product Manager",
    experienceLevel: "Senior Level",
    skills: [
      "Product Management",
      "Agile",
      "Roadmapping",
      "Stakeholder Management",
    ],
    title: "Senior Product Manager — B2B SaaS",
    email: "elena.petrova@example.com",
    phone: "+7-495-000-0006",
    summary:
      "10+ years managing product strategy and cross-functional teams in SaaS companies.",
    location: "Moscow, Russia",
    cv_score: 84,
    cv_match_percentage: 79,
    availability_status: "Open to Offers",
    expected_salary: 150000,
    work_preference: "hybrid",
    linkedin_url: "https://linkedin.com/in/elenapetrova",
    portfolio_url: null,
    github_url: null,
    avatarUrl: null,
    created_at: new Date("2022-07-20T10:00:00Z"),
    updated_at: new Date("2025-11-30T08:45:00Z"),
  },

  {
    id: "cand-7",
    user_id: "u7",
    name: "David Kim",
    jobTitle: "Frontend Developer",
    experienceLevel: "Entry Level",
    skills: ["React", "JavaScript", "CSS", "Next.js"],
    title: "Junior Frontend Developer",
    email: "david.kim@example.com",
    phone: "+82-10-0000-0007",
    summary:
      "Recent graduate focused on modern frontend stacks and UI performance.",
    location: "Seoul, South Korea",
    cv_score: 58,
    cv_match_percentage: 55,
    availability_status: "Available",
    expected_salary: 50000,
    work_preference: "on-site",
    linkedin_url: "https://linkedin.com/in/davidkim",
    portfolio_url: "https://davidkim.design",
    github_url: "https://github.com/davidkimdev",
    avatarUrl: null,
    created_at: new Date("2025-05-01T12:00:00Z"),
    updated_at: new Date("2025-12-15T09:00:00Z"),
  },

  {
    id: "cand-8",
    user_id: "u8",
    name: "Priya Singh",
    jobTitle: "DevOps Engineer",
    experienceLevel: "Senior Level",
    skills: ["AWS", "Terraform", "Kubernetes", "Docker", "CI/CD"],
    title: "Senior DevOps Engineer — Cloud Infrastructure",
    email: "priya.singh@example.com",
    phone: "+91-98765-00008",
    summary:
      "Focused on scalable cloud infrastructure, automation and platform reliability.",
    location: "Bengaluru, India",
    cv_score: 82,
    cv_match_percentage: 85,
    availability_status: "Available",
    expected_salary: 140000,
    work_preference: "remote",
    linkedin_url: "https://linkedin.com/in/priyasingh-devops",
    portfolio_url: null,
    github_url: null,
    avatarUrl: null,
    created_at: new Date("2024-10-10T07:30:00Z"),
    updated_at: new Date("2026-01-20T11:10:00Z"),
  },

  {
    id: "cand-9",
    user_id: "u9",
    name: "Lucas Müller",
    jobTitle: "UX Designer",
    experienceLevel: "Lead",
    skills: ["Figma", "UX Research", "Prototyping", "Design Systems"],
    title: "Lead UX Designer — Product Design",
    email: "lucas.muller@example.com",
    phone: "+49-30-0000-0009",
    summary:
      "Leads cross-functional design teams; builds design systems and runs user research.",
    location: "Berlin, Germany",
    cv_score: 72,
    cv_match_percentage: 70,
    availability_status: "Open to Offers",
    expected_salary: 120000,
    work_preference: "hybrid",
    linkedin_url: "https://linkedin.com/in/lucasmuller",
    portfolio_url: "https://lucasmuller.design",
    github_url: null,
    avatarUrl: null,
    created_at: new Date("2023-04-18T09:00:00Z"),
    updated_at: new Date("2025-08-22T10:00:00Z"),
  },

  {
    id: "cand-10",
    user_id: "u10",
    name: "Nora Ibrahim",
    jobTitle: "Chief Data Officer",
    experienceLevel: "Executive",
    skills: ["Data Strategy", "Machine Learning", "Leadership", "MLOps"],
    title: "Executive — Data & AI",
    email: "nora.ibrahim@example.com",
    phone: "+44-20-0000-0010",
    summary:
      "Executive leader with experience scaling data organizations and delivering AI-driven products.",
    location: "London, UK",
    cv_score: 98,
    cv_match_percentage: 88,
    availability_status: "Not Available",
    expected_salary: 250000,
    work_preference: "other",
    linkedin_url: "https://linkedin.com/in/noraibrahim",
    portfolio_url: null,
    github_url: null,
    avatarUrl: null,
    created_at: new Date("2020-01-05T08:00:00Z"),
    updated_at: new Date("2025-06-30T14:00:00Z"),
  },

  {
    id: "cand-11",
    user_id: "u11",
    name: "Mateo Santos",
    jobTitle: "QA Engineer",
    experienceLevel: "Mid Level",
    skills: ["Testing", "Selenium", "Cypress", "JavaScript"],
    title: "Quality Assurance Engineer",
    email: "mateo.santos@example.com",
    phone: "+52-55-0000-0011",
    summary:
      "QA engineer focused on E2E automation and improving test coverage in complex web apps.",
    location: "Mexico City, Mexico",
    cv_score: 68,
    cv_match_percentage: 64,
    availability_status: "Available",
    expected_salary: 70000,
    work_preference: "on-site",
    linkedin_url: "https://linkedin.com/in/mateosantos",
    portfolio_url: null,
    github_url: "https://github.com/mateosantosqa",
    avatarUrl: null,
    created_at: new Date("2024-01-25T10:30:00Z"),
    updated_at: new Date("2025-12-20T09:15:00Z"),
  },

  {
    id: "cand-12",
    user_id: "u12",
    name: "Aisha Khan",
    jobTitle: "Software Engineer",
    experienceLevel: "Senior Level",
    skills: ["Go", "Kubernetes", "Distributed Systems", "gRPC"],
    title: "Senior Software Engineer — Distributed Systems",
    email: "aisha.khan@example.com",
    phone: "+44-7700-00012",
    summary:
      "Experienced in building low-latency, distributed services and backend platforms.",
    location: "London, UK",
    cv_score: 90,
    cv_match_percentage: 87,
    availability_status: "Open to Offers",
    expected_salary: 145000,
    work_preference: "hybrid",
    linkedin_url: "https://linkedin.com/in/aishakhan",
    portfolio_url: "https://aishak.dev",
    github_url: "https://github.com/aishak",
    avatarUrl: null,
    created_at: new Date("2021-08-09T09:45:00Z"),
    updated_at: new Date("2026-01-12T10:00:00Z"),
  },
];
