export const floatingCompanies = [
  {
    src: "/companies/google-icon.svg",
    alt: "Google",
    width: 48,
    height: 48,
    position: "left-[15%] top-[10%]",
    animation: "float-slow",
  },
  {
    src: "/companies/meta-icon.svg",
    alt: "Meta",
    width: 64,
    height: 48,
    position: "right-[6%] top-[13%]",
    animation: "float-medium",
  },
  {
    src: "/companies/microsoft-icon.svg",
    alt: "Microsoft",
    width: 48,
    height: 48,
    position: "left-[3%] top-[45%]",
    animation: "float-fast",
  },
  {
    src: "/companies/netflix-icon.svg",
    alt: "Netflix",
    width: 48,
    height: 48,
    position: "right-[3%] bottom-[10%]",
    animation: "float-slow",
  },
  {
    src: "/companies/spotify-icon.svg",
    alt: "Spotify",
    width: 52,
    height: 52,
    position: "bottom-[10%] left-[10%]",
    animation: "float-medium",
  },
  {
    src: "/companies/apple.svg",
    alt: "Apple",
    width: 48,
    height: 48,
    position: "bottom-[35%] right-[15%]",
    animation: "float-fast",
  },
  {
    src: "/companies/zoom-icon.svg",
    alt: "Zoom",
    width: 48,
    height: 48,
    position: "left-[35%] top-[15%]",
    animation: "float-medium",
  },
  {
    src: "/companies/airbnb-icon.svg",
    alt: "Airbnb",
    width: 58,
    height: 58,
    position: "right-[35%] bottom-[30%]",
    animation: "float-slow",
  },
];
