import { Candidate } from "../types/candidate";

export const allJobSeekers: Candidate[] = [
  {
    jobSeekerId: "js-1",
    firstName: "Amina",
    lastName: "Hassan",
    title: "Frontend Engineer",
    skills: [
      { name: "React", verified: true },
      { name: "TypeScript", verified: true },
      { name: "Next.js", verified: false },
      { name: "CSS", verified: false },
      { name: "Tailwind", verified: false },
    ],
    email: "amina.hassan@example.com",
    phone: "+20-100-000-0001",
    summary:
      "4+ years building responsive web apps and component libraries. Strong focus on performance and accessibility.",
    location: "Cairo, Egypt",
    cvScore: 72,
    cvMatchPercentage: 68,
    availabilityStatus: "Open to Offers",
    expectedSalary: 60000,
    workPreference: "hybrid",
    linkedinUrl: "https://linkedin.com/in/amina-hassan",
    portfolioUrl: "https://amina.dev",
    githubUrl: "https://github.com/aminahassan",
    avatarUrl: null,
    experienceLevel: "Mid Level",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-2",
    firstName: "John",
    lastName: "Carter",
    title: "Backend Engineer",
    skills: [
      { name: "Node.js", verified: true },
      { name: "TypeScript", verified: true },
      { name: "PostgreSQL", verified: true },
      { name: "Docker", verified: false },
      { name: "AWS", verified: false },
    ],
    email: "john.carter@example.com",
    phone: "+1-415-555-0123",
    summary:
      "Backend engineer with a track record of building high-throughput services and microservice architectures.",
    location: "San Francisco, CA, USA",
    cvScore: 88,
    cvMatchPercentage: 91,
    availabilityStatus: "Available",
    expectedSalary: 130000,
    workPreference: "remote",
    linkedinUrl: "https://linkedin.com/in/johncarter",
    portfolioUrl: null,
    githubUrl: "https://github.com/johncarter-dev",
    avatarUrl: null,
    experienceLevel: "Senior Level",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-3",

    firstName: "Maria",
    lastName: "Lopez",
    title: "Data Analyst",
    skills: [
      { name: "SQL", verified: true },
      { name: "Python", verified: false },
      { name: "Pandas", verified: false },
      { name: "Excel", verified: false },
      { name: "Tableau", verified: false },
    ],
    email: "maria.lopez@example.com",
    phone: null,
    summary:
      "Entry-level analyst with internship experience in data cleaning, visualization and reporting.",
    location: "Bogota, Colombia",
    cvScore: 65,
    cvMatchPercentage: 60,
    availabilityStatus: "Open to Offers",
    expectedSalary: 48000,
    workPreference: "on-site",
    linkedinUrl: "https://linkedin.com/in/marialopez",
    portfolioUrl: null,
    githubUrl: "https://github.com/marialopez",
    avatarUrl: null,
    experienceLevel: "Entry Level",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-4",

    firstName: "Chen",
    lastName: "Wei",
    title: "Machine Learning Engineer",
    skills: [
      { name: "Python", verified: true },
      { name: "TensorFlow", verified: true },
      { name: "PyTorch", verified: true },
      { name: "ML Ops", verified: false },
      { name: "Kubernetes", verified: false },
    ],
    email: "chen.wei@example.com",
    phone: "+86-10-8888-0004",
    summary:
      "Led ML platform initiatives and productionized several large-scale models for recommendation and forecasting.",
    location: "Beijing, China",
    cvScore: 95,
    cvMatchPercentage: 92,
    availabilityStatus: "Not Available",
    expectedSalary: 180000,
    workPreference: "hybrid",
    linkedinUrl: "https://linkedin.com/in/chenwei-ml",
    portfolioUrl: null,
    githubUrl: "https://github.com/chenwei-ml",
    avatarUrl: null,
    experienceLevel: "Lead",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-5",

    firstName: "Samuel",
    lastName: "Okoye",
    title: "Fullstack Developer",
    skills: [
      { name: "React", verified: true },
      { name: "Node.js", verified: true },
      { name: "GraphQL", verified: false },
      { name: "TypeScript", verified: true },
      { name: "Prisma", verified: false },
    ],
    email: "samuel.okoye@example.com",
    phone: "+234-80-0000-0005",
    summary:
      "Fullstack developer experienced in end-to-end feature delivery and API design.",
    location: "Lagos, Nigeria",
    cvScore: 77,
    cvMatchPercentage: 73,
    availabilityStatus: "Available",
    expectedSalary: 80000,
    workPreference: "remote",
    linkedinUrl: "https://linkedin.com/in/samuelokoye",
    portfolioUrl: "https://samuel.dev",
    githubUrl: "https://github.com/samuelokoye",
    avatarUrl: null,
    experienceLevel: "Mid Level",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-6",

    firstName: "Elena",
    lastName: "Petrova",
    title: "Product Manager",
    skills: [
      { name: "Product Management", verified: false },
      { name: "Agile", verified: false },
      { name: "Roadmapping", verified: false },
      { name: "Stakeholder Management", verified: false },
    ],
    email: "elena.petrova@example.com",
    phone: "+7-495-000-0006",
    summary:
      "10+ years managing product strategy and cross-functional teams in SaaS companies.",
    location: "Moscow, Russia",
    cvScore: 84,
    cvMatchPercentage: 79,
    availabilityStatus: "Open to Offers",
    expectedSalary: 150000,
    workPreference: "hybrid",
    linkedinUrl: "https://linkedin.com/in/elenapetrova",
    portfolioUrl: null,
    githubUrl: null,
    avatarUrl: null,
    experienceLevel: "Senior Level",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-7",

    firstName: "David",
    lastName: "Kim",
    title: "Frontend Developer",
    skills: [
      { name: "React", verified: true },
      { name: "JavaScript", verified: false },
      { name: "CSS", verified: false },
      { name: "Next.js", verified: false },
    ],
    email: "david.kim@example.com",
    phone: "+82-10-0000-0007",
    summary:
      "Recent graduate focused on modern frontend stacks and UI performance.",
    location: "Seoul, South Korea",
    cvScore: 58,
    cvMatchPercentage: 55,
    availabilityStatus: "Available",
    expectedSalary: 50000,
    workPreference: "on-site",
    linkedinUrl: "https://linkedin.com/in/davidkim",
    portfolioUrl: "https://davidkim.design",
    githubUrl: "https://github.com/davidkimdev",
    avatarUrl: null,
    experienceLevel: "Entry Level",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-8",

    firstName: "Priya",
    lastName: "Singh",
    title: "DevOps Engineer",
    skills: [
      { name: "AWS", verified: true },
      { name: "Terraform", verified: false },
      { name: "Kubernetes", verified: true },
      { name: "Docker", verified: true },
      { name: "CI/CD", verified: false },
    ],
    email: "priya.singh@example.com",
    phone: "+91-98765-00008",
    summary:
      "Focused on scalable cloud infrastructure, automation and platform reliability.",
    location: "Bengaluru, India",
    cvScore: 82,
    cvMatchPercentage: 85,
    availabilityStatus: "Available",
    expectedSalary: 140000,
    workPreference: "remote",
    linkedinUrl: "https://linkedin.com/in/priyasingh-devops",
    portfolioUrl: null,
    githubUrl: null,
    avatarUrl: null,
    experienceLevel: "Senior Level",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-9",

    firstName: "Lucas",
    lastName: "Muller",
    title: "UX Designer",
    skills: [
      { name: "Figma", verified: true },
      { name: "UX Research", verified: false },
      { name: "Prototyping", verified: false },
      { name: "Design Systems", verified: false },
    ],
    email: "lucas.muller@example.com",
    phone: "+49-30-0000-0009",
    summary:
      "Leads cross-functional design teams; builds design systems and runs user research.",
    location: "Berlin, Germany",
    cvScore: 72,
    cvMatchPercentage: 70,
    availabilityStatus: "Open to Offers",
    expectedSalary: 120000,
    workPreference: "hybrid",
    linkedinUrl: "https://linkedin.com/in/lucasmuller",
    portfolioUrl: "https://lucasmuller.design",
    githubUrl: null,
    avatarUrl: null,
    experienceLevel: "Lead",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-10",

    firstName: "Nora",
    lastName: "Ibrahim",
    title: "Chief Data Officer",
    skills: [
      { name: "Data Strategy", verified: false },
      { name: "Machine Learning", verified: true },
      { name: "Leadership", verified: false },
      { name: "MLOps", verified: false },
    ],
    email: "nora.ibrahim@example.com",
    phone: "+44-20-0000-0010",
    summary:
      "Executive leader with experience scaling data organizations and delivering AI-driven products.",
    location: "London, UK",
    cvScore: 98,
    cvMatchPercentage: 88,
    availabilityStatus: "Not Available",
    expectedSalary: 250000,
    workPreference: "other",
    linkedinUrl: "https://linkedin.com/in/noraibrahim",
    portfolioUrl: null,
    githubUrl: null,
    avatarUrl: null,
    experienceLevel: "Executive",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-11",

    firstName: "Mateo",
    lastName: "Santos",
    title: "QA Engineer",
    skills: [
      { name: "Testing", verified: false },
      { name: "Selenium", verified: false },
      { name: "Cypress", verified: true },
      { name: "JavaScript", verified: false },
    ],
    email: "mateo.santos@example.com",
    phone: "+52-55-0000-0011",
    summary:
      "QA engineer focused on E2E automation and improving test coverage in complex web apps.",
    location: "Mexico City, Mexico",
    cvScore: 68,
    cvMatchPercentage: 64,
    availabilityStatus: "Available",
    expectedSalary: 70000,
    workPreference: "on-site",
    linkedinUrl: "https://linkedin.com/in/mateosantos",
    portfolioUrl: null,
    githubUrl: "https://github.com/mateosantosqa",
    avatarUrl: null,
    experienceLevel: "Mid Level",
    cvUrl: null,
  },
  {
    jobSeekerId: "js-12",

    firstName: "Aisha",
    lastName: "Khan",
    title: "Software Engineer",
    skills: [
      { name: "Go", verified: true },
      { name: "Kubernetes", verified: true },
      { name: "Distributed Systems", verified: false },
      { name: "gRPC", verified: false },
    ],
    email: "aisha.khan@example.com",
    phone: "+44-7700-00012",
    summary:
      "Experienced in building low-latency, distributed services and backend platforms.",
    location: "London, UK",
    cvScore: 90,
    cvMatchPercentage: 87,
    availabilityStatus: "Open to Offers",
    expectedSalary: 145000,
    workPreference: "hybrid",
    linkedinUrl: "https://linkedin.com/in/aishakhan",
    portfolioUrl: "https://aishak.dev",
    githubUrl: "https://github.com/aishak",
    avatarUrl: null,
    experienceLevel: "Senior Level",
    cvUrl: null,
  },
];
