import { JobSeeker } from "../types/jobSeeker";

export const allJobSeekers: JobSeeker[] = [
  {
    firstName: "Amina",
    lastName: "Hassan",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-1",
      title: "Frontend Engineer",
      location: "Cairo, Egypt",
      availabilityStatus: "OPEN_TO_WORK",
      workPreference: "HYBRID",
      preferredJobTypes: ["FREELANCE", "FULL_TIME"],
      yearsOfExperience: 4,
      linkedinUrl: "https://linkedin.com/in/amina-hassan",
      portfolioUrl: "https://amina.dev",
      githubUrl: "https://github.com/aminahassan",
      email: "amina.hassan@example.com",
      phone: "+20-100-000-0001",
      expectedSalary: 60000,
      summary:
        "4+ years building responsive web apps and component libraries. Strong focus on performance and accessibility.",
      cvScore: 72,
      cvMatchPercentage: 68,
      cvUrl: null,
    },
    skills: [
      { name: "React", verified: true },
      { name: "TypeScript", verified: true },
      { name: "Next.js", verified: false },
      { name: "CSS", verified: false },
      { name: "Tailwind", verified: false },
    ],
  },
  {
    firstName: "John",
    lastName: "Carter",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-2",
      title: "Backend Engineer",
      location: "San Francisco, CA, USA",
      availabilityStatus: "OPEN_TO_WORK",
      workPreference: "REMOTE",
      preferredJobTypes: ["FREELANCE", "FULL_TIME"],
      yearsOfExperience: 8,
      linkedinUrl: "https://linkedin.com/in/johncarter",
      portfolioUrl: null,
      githubUrl: "https://github.com/johncarter-dev",
      email: "john.carter@example.com",
      phone: "+1-415-555-0123",
      expectedSalary: 130000,
      summary:
        "Backend engineer with a track record of building high-throughput services and microservice architectures.",
      cvScore: 88,
      cvMatchPercentage: 91,
      cvUrl: null,
    },
    skills: [
      { name: "Node.js", verified: true },
      { name: "TypeScript", verified: true },
      { name: "PostgreSQL", verified: true },
      { name: "Docker", verified: false },
      { name: "AWS", verified: false },
    ],
  },
  {
    firstName: "Maria",
    lastName: "Lopez",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-3",
      title: "Data Analyst",
      location: "Bogota, Colombia",
      availabilityStatus: "PASSIVELY_LOOKING",
      workPreference: "ONSITE",
      preferredJobTypes: [],
      yearsOfExperience: 2,
      linkedinUrl: "https://linkedin.com/in/marialopez",
      portfolioUrl: null,
      githubUrl: "https://github.com/marialopez",
      email: "maria.lopez@example.com",
      phone: null,
      expectedSalary: 48000,
      summary:
        "Entry-level analyst with internship experience in data cleaning, visualization and reporting.",
      cvScore: 65,
      cvMatchPercentage: 60,
      cvUrl: null,
    },
    skills: [
      { name: "SQL", verified: true },
      { name: "Python", verified: false },
      { name: "Pandas", verified: false },
      { name: "Excel", verified: false },
      { name: "Tableau", verified: false },
    ],
  },
  {
    firstName: "Chen",
    lastName: "Wei",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-4",
      title: "Machine Learning Engineer",
      location: "Beijing, China",
      availabilityStatus: "NOT_LOOKING",
      workPreference: "HYBRID",
      preferredJobTypes: [],
      yearsOfExperience: 10,
      linkedinUrl: "https://linkedin.com/in/chenwei-ml",
      portfolioUrl: null,
      githubUrl: "https://github.com/chenwei-ml",
      email: "chen.wei@example.com",
      phone: "+86-10-8888-0004",
      expectedSalary: 180000,
      summary:
        "Led ML platform initiatives and productionized several large-scale models for recommendation and forecasting.",
      cvScore: 95,
      cvMatchPercentage: 92,
      cvUrl: null,
    },
    skills: [
      { name: "Python", verified: true },
      { name: "TensorFlow", verified: true },
      { name: "PyTorch", verified: true },
      { name: "ML Ops", verified: false },
      { name: "Kubernetes", verified: false },
    ],
  },
  {
    firstName: "Samuel",
    lastName: "Okoye",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-5",
      title: "Fullstack Developer",
      location: "Lagos, Nigeria",
      availabilityStatus: "OPEN_TO_WORK",
      workPreference: "REMOTE",
      preferredJobTypes: [],
      yearsOfExperience: 5,
      linkedinUrl: "https://linkedin.com/in/samuelokoye",
      portfolioUrl: "https://samuel.dev",
      githubUrl: "https://github.com/samuelokoye",
      email: "samuel.okoye@example.com",
      phone: "+234-80-0000-0005",
      expectedSalary: 80000,
      summary:
        "Fullstack developer experienced in end-to-end feature delivery and API design.",
      cvScore: 77,
      cvMatchPercentage: 73,
      cvUrl: null,
    },
    skills: [
      { name: "React", verified: true },
      { name: "Node.js", verified: true },
      { name: "GraphQL", verified: false },
      { name: "TypeScript", verified: true },
      { name: "Prisma", verified: false },
    ],
  },
  {
    firstName: "Elena",
    lastName: "Petrova",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-6",
      title: "Product Manager",
      location: "Moscow, Russia",
      availabilityStatus: "PASSIVELY_LOOKING",
      workPreference: "HYBRID",
      preferredJobTypes: [],
      yearsOfExperience: 10,
      linkedinUrl: "https://linkedin.com/in/elenapetrova",
      portfolioUrl: null,
      githubUrl: null,
      email: "elena.petrova@example.com",
      phone: "+7-495-000-0006",
      expectedSalary: 150000,
      summary:
        "10+ years managing product strategy and cross-functional teams in SaaS companies.",
      cvScore: 84,
      cvMatchPercentage: 79,
      cvUrl: null,
    },
    skills: [
      { name: "Product Management", verified: false },
      { name: "Agile", verified: false },
      { name: "Roadmapping", verified: false },
      { name: "Stakeholder Management", verified: false },
    ],
  },
  {
    firstName: "David",
    lastName: "Kim",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-7",
      title: "Frontend Developer",
      location: "Seoul, South Korea",
      availabilityStatus: "OPEN_TO_WORK",
      workPreference: "ONSITE",
      preferredJobTypes: [],
      yearsOfExperience: 1,
      linkedinUrl: "https://linkedin.com/in/davidkim",
      portfolioUrl: "https://davidkim.design",
      githubUrl: "https://github.com/davidkimdev",
      email: "david.kim@example.com",
      phone: "+82-10-0000-0007",
      expectedSalary: 50000,
      summary:
        "Recent graduate focused on modern frontend stacks and UI performance.",
      cvScore: 58,
      cvMatchPercentage: 55,
      cvUrl: null,
    },
    skills: [
      { name: "React", verified: true },
      { name: "JavaScript", verified: false },
      { name: "CSS", verified: false },
      { name: "Next.js", verified: false },
    ],
  },
  {
    firstName: "Priya",
    lastName: "Singh",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-8",
      title: "DevOps Engineer",
      location: "Bengaluru, India",
      availabilityStatus: "OPEN_TO_WORK",
      workPreference: "REMOTE",
      preferredJobTypes: [],
      yearsOfExperience: 10,
      linkedinUrl: "https://linkedin.com/in/priyasingh-devops",
      portfolioUrl: null,
      githubUrl: null,
      email: "priya.singh@example.com",
      phone: "+91-98765-00008",
      expectedSalary: 140000,
      summary:
        "Focused on scalable cloud infrastructure, automation and platform reliability.",
      cvScore: 82,
      cvMatchPercentage: 85,
      cvUrl: null,
    },
    skills: [
      { name: "AWS", verified: true },
      { name: "Terraform", verified: false },
      { name: "Kubernetes", verified: true },
      { name: "Docker", verified: true },
      { name: "CI/CD", verified: false },
    ],
  },
  {
    firstName: "Lucas",
    lastName: "Muller",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-9",
      title: "UX Designer",
      location: "Berlin, Germany",
      availabilityStatus: "PASSIVELY_LOOKING",
      workPreference: "HYBRID",
      preferredJobTypes: [],
      yearsOfExperience: 10,
      linkedinUrl: "https://linkedin.com/in/lucasmuller",
      portfolioUrl: "https://lucasmuller.design",
      githubUrl: null,
      email: "lucas.muller@example.com",
      phone: "+49-30-0000-0009",
      expectedSalary: 120000,
      summary:
        "Leads cross-functional design teams; builds design systems and runs user research.",
      cvScore: 72,
      cvMatchPercentage: 70,
      cvUrl: null,
    },
    skills: [
      { name: "Figma", verified: true },
      { name: "UX Research", verified: false },
      { name: "Prototyping", verified: false },
      { name: "Design Systems", verified: false },
    ],
  },
  {
    firstName: "Nora",
    lastName: "Ibrahim",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-10",
      title: "Chief Data Officer",
      location: "London, UK",
      availabilityStatus: "NOT_LOOKING",
      workPreference: "ANY",
      preferredJobTypes: [],
      yearsOfExperience: 15,
      linkedinUrl: "https://linkedin.com/in/noraibrahim",
      portfolioUrl: null,
      githubUrl: null,
      email: "nora.ibrahim@example.com",
      phone: "+44-20-0000-0010",
      expectedSalary: 250000,
      summary:
        "Executive leader with experience scaling data organizations and delivering AI-driven products.",
      cvScore: 98,
      cvMatchPercentage: 88,
      cvUrl: null,
    },
    skills: [
      { name: "Data Strategy", verified: false },
      { name: "Machine Learning", verified: true },
      { name: "Leadership", verified: false },
      { name: "MLOps", verified: false },
    ],
  },
  {
    firstName: "Mateo",
    lastName: "Santos",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-11",
      title: "QA Engineer",
      location: "Mexico City, Mexico",
      availabilityStatus: "OPEN_TO_WORK",
      workPreference: "ONSITE",
      preferredJobTypes: [],
      yearsOfExperience: 5,
      linkedinUrl: "https://linkedin.com/in/mateosantos",
      portfolioUrl: null,
      githubUrl: "https://github.com/mateosantosqa",
      email: "mateo.santos@example.com",
      phone: "+52-55-0000-0011",
      expectedSalary: 70000,
      summary:
        "QA engineer focused on E2E automation and improving test coverage in complex web apps.",
      cvScore: 68,
      cvMatchPercentage: 64,
      cvUrl: null,
    },
    skills: [
      { name: "Testing", verified: false },
      { name: "Selenium", verified: false },
      { name: "Cypress", verified: true },
      { name: "JavaScript", verified: false },
    ],
  },
  {
    firstName: "Aisha",
    lastName: "Khan",
    profileImageUrl: null,
    profile: {
      jobSeekerId: "js-12",
      title: "Software Engineer",
      location: "London, UK",
      availabilityStatus: "PASSIVELY_LOOKING",
      workPreference: "HYBRID",
      preferredJobTypes: [],
      yearsOfExperience: 10,
      linkedinUrl: "https://linkedin.com/in/aishakhan",
      portfolioUrl: "https://aishak.dev",
      githubUrl: "https://github.com/aishak",
      email: "aisha.khan@example.com",
      phone: "+44-7700-00012",
      expectedSalary: 145000,
      summary:
        "Experienced in building low-latency, distributed services and backend platforms.",
      cvScore: 90,
      cvMatchPercentage: 87,
      cvUrl: null,
    },
    skills: [
      { name: "Go", verified: true },
      { name: "Kubernetes", verified: true },
      { name: "Distributed Systems", verified: false },
      { name: "gRPC", verified: false },
    ],
  },
];
