import { JobApplication } from "../type/application";

export const mockApplications: JobApplication[] = [
  {
    id: "app-1",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-2",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-3",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-4",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-5",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-6",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-31",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-32",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-33",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-34",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-35",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-36",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-7",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-8",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-9",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-10",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-11",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-12",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-13",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-14",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-15",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-16",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-17",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-18",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-19",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-20",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-21",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-22",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-23",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-24",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-25",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-26",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-27",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_001",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-28",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_002",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
  {
    id: "app-29",
    status: "PENDING",
    appliedAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-02-21T14:30:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-1",
      firstName: "John",
      lastName: "Doe",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "john@example.com",
      profile: {
        title: "Software Engineer",
        summary: "Experienced software engineer",
        location: "Cairo, Egypt",
        yearsOfExperience: 3,
        availabilityStatus: "Available",
        workPreference: "REMOTE",
        expectedSalary: 20000,
        linkedinUrl: "https://linkedin.com/in/johndoe",
        githubUrl: "https://github.com/johndoe",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s1", name: "TypeScript", verified: true },
        { id: "s2", name: "Node.js", verified: true },
      ],
    },
  },
  {
    id: "app-30",
    status: "REVIEWED",
    appliedAt: "2025-02-18T09:00:00Z",
    updatedAt: "2025-02-19T11:00:00Z",
    directJob: {
      id: "job_003",
      title: "Senior Software Engineer",
    },
    jobSeeker: {
      id: "js-2",
      firstName: "Sara",
      lastName: "Ahmed",
      profileImageUrl: "/about/job-seeker-illustration.webp",
      email: "sara@example.com",
      profile: {
        title: "Frontend Developer",
        summary: "React developer",
        location: "Alexandria, Egypt",
        yearsOfExperience: 2,
        availabilityStatus: "Available",
        workPreference: "HYBRID",
        expectedSalary: 15000,
        linkedinUrl: "https://linkedin.com/in/sara",
        githubUrl: "https://github.com/sara",
        cvMatchPercentage: 90,
        email: "",
        phone: "00000000000",
        cvScore: 90,
        cvUrl: "https://example.com/cv/john.pdf",
      },

      skills: [
        { id: "s3", name: "React", verified: true },
        { id: "s4", name: "TypeScript", verified: true },
      ],
    },
  },
];
